FROM goslar/sessiondriver:latest AS session-driver
FROM alpine:3 AS gecko-fetcher

WORKDIR /build

RUN apk update
RUN apk add wget tar
RUN apk add ca-certificates
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
RUN tar -xvzf geckodriver*
RUN chmod +x geckodriver

FROM jlesage/firefox:v25.07.1

RUN apk update && \
      apk add wget

COPY --from=gecko-fetcher /build/geckodriver /bin/geckodriver
COPY --from=session-driver /usr/local/bin/sessiondriver-musl /bin/sessiondriver

HEALTHCHECK --interval=15s --timeout=10s --retries=3 CMD wget --spider -q http://127.0.0.1:4444/status || exit 1

EXPOSE 4444

ENTRYPOINT [ "sessiondriver" ]
CMD [ "--port=4444", "--host=0.0.0.0", "--webdriver=geckodriver", "--parameters=--allow-hosts=*" ]

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                                                     #
#     docker build -t goslar/sessiondriver-firefox:latest -f ./Dockerfile-SessionDriver-Firefox .     #
#                                                                                                     #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #