name: docker.yml
on:
  push:
    tags:
      - '**'

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build SessionDriver
        run: docker build -t goslar/sessiondriver:${{ github.ref_name }} -f Dockerfile .
      - name: Push Tag
        run: docker push goslar/sessiondriver:${{ github.ref_name }}
      - name: Create Manifest
        run: docker manifest create goslar/sessiondriver:latest goslar/sessiondriver:${{ github.ref_name }}
      - name: Push Manifest
        run: docker manifest push goslar/sessiondriver:latest

      - name: Layer SessionDriver, Firefox and geckodriver
        run: docker build -t goslar/sessiondriver-firefox:${{ github.ref_name }} -f Dockerfile-SessionDriver-Firefox .
      - name: Push Tag
        run: docker push goslar/sessiondriver-firefox:${{ github.ref_name }}
      - name: Create Manifest
        run: docker manifest create goslar/sessiondriver-firefox:latest goslar/sessiondriver-firefox:${{ github.ref_name }}
      - name: Push Manifest
        run: docker manifest push goslar/sessiondriver-firefox:latest